<?php
/**
 * LoadCarrier
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * LoadCarrier Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LoadCarrier implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LoadCarrier';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sscc' => 'string',
        'transport_label_track_and_trace' => 'string',
        'transport_state' => 'string',
        'transport_state_update_date_time' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sscc' => null,
        'transport_label_track_and_trace' => null,
        'transport_state' => null,
        'transport_state_update_date_time' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sscc' => 'sscc',
        'transport_label_track_and_trace' => 'transportLabelTrackAndTrace',
        'transport_state' => 'transportState',
        'transport_state_update_date_time' => 'transportStateUpdateDateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sscc' => 'setSscc',
        'transport_label_track_and_trace' => 'setTransportLabelTrackAndTrace',
        'transport_state' => 'setTransportState',
        'transport_state_update_date_time' => 'setTransportStateUpdateDateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sscc' => 'getSscc',
        'transport_label_track_and_trace' => 'getTransportLabelTrackAndTrace',
        'transport_state' => 'getTransportState',
        'transport_state_update_date_time' => 'getTransportStateUpdateDateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TRANSPORT_STATE_ANNOUNCED = 'ANNOUNCED';
    const TRANSPORT_STATE_PICKED_UP = 'PICKED_UP';
    const TRANSPORT_STATE_UNDERWAY = 'UNDERWAY';
    const TRANSPORT_STATE_DELAYED = 'DELAYED';
    const TRANSPORT_STATE_ARRIVED = 'ARRIVED';
    const TRANSPORT_STATE_ERROR = 'ERROR';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTransportStateAllowableValues()
    {
        return [
            self::TRANSPORT_STATE_ANNOUNCED,
            self::TRANSPORT_STATE_PICKED_UP,
            self::TRANSPORT_STATE_UNDERWAY,
            self::TRANSPORT_STATE_DELAYED,
            self::TRANSPORT_STATE_ARRIVED,
            self::TRANSPORT_STATE_ERROR,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sscc'] = isset($data['sscc']) ? $data['sscc'] : null;
        $this->container['transport_label_track_and_trace'] = isset($data['transport_label_track_and_trace']) ? $data['transport_label_track_and_trace'] : null;
        $this->container['transport_state'] = isset($data['transport_state']) ? $data['transport_state'] : null;
        $this->container['transport_state_update_date_time'] = isset($data['transport_state_update_date_time']) ? $data['transport_state_update_date_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['transport_state'] === null) {
            $invalidProperties[] = "'transport_state' can't be null";
        }
        $allowedValues = $this->getTransportStateAllowableValues();
        if (!is_null($this->container['transport_state']) && !in_array($this->container['transport_state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'transport_state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['transport_state_update_date_time'] === null) {
            $invalidProperties[] = "'transport_state_update_date_time' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sscc
     *
     * @return string
     */
    public function getSscc()
    {
        return $this->container['sscc'];
    }

    /**
     * Sets sscc
     *
     * @param string $sscc The Serial Shipping Container Code (SSCC) for this load carrier.
     *
     * @return $this
     */
    public function setSscc($sscc)
    {
        $this->container['sscc'] = $sscc;

        return $this;
    }

    /**
     * Gets transport_label_track_and_trace
     *
     * @return string
     */
    public function getTransportLabelTrackAndTrace()
    {
        return $this->container['transport_label_track_and_trace'];
    }

    /**
     * Sets transport_label_track_and_trace
     *
     * @param string $transport_label_track_and_trace The track and trace code for this load carrier.
     *
     * @return $this
     */
    public function setTransportLabelTrackAndTrace($transport_label_track_and_trace)
    {
        $this->container['transport_label_track_and_trace'] = $transport_label_track_and_trace;

        return $this;
    }

    /**
     * Gets transport_state
     *
     * @return string
     */
    public function getTransportState()
    {
        return $this->container['transport_state'];
    }

    /**
     * Sets transport_state
     *
     * @param string $transport_state The current state of the transport for this load carrier.
     *
     * @return $this
     */
    public function setTransportState($transport_state)
    {
        $allowedValues = $this->getTransportStateAllowableValues();
        if (!in_array($transport_state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'transport_state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['transport_state'] = $transport_state;

        return $this;
    }

    /**
     * Gets transport_state_update_date_time
     *
     * @return \DateTime
     */
    public function getTransportStateUpdateDateTime()
    {
        return $this->container['transport_state_update_date_time'];
    }

    /**
     * Sets transport_state_update_date_time
     *
     * @param \DateTime $transport_state_update_date_time The date and time in ISO 8601 format when the latest update for this transport was received.
     *
     * @return $this
     */
    public function setTransportStateUpdateDateTime($transport_state_update_date_time)
    {
        $this->container['transport_state_update_date_time'] = $transport_state_update_date_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


