<?php
/**
 * CreateReplenishmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateReplenishmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateReplenishmentRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateReplenishmentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateReplenishmentRequest"
     */
    public function testCreateReplenishmentRequest()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "delivery_info"
     */
    public function testPropertyDeliveryInfo()
    {
    }

    /**
     * Test attribute "labeling_by_bol"
     */
    public function testPropertyLabelingByBol()
    {
    }

    /**
     * Test attribute "number_of_load_carriers"
     */
    public function testPropertyNumberOfLoadCarriers()
    {
    }

    /**
     * Test attribute "pickup_appointment"
     */
    public function testPropertyPickupAppointment()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }
}
