<?php
/**
 * HandoverDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HandoverDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description HandoverDetails
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HandoverDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HandoverDetails"
     */
    public function testHandoverDetails()
    {
    }

    /**
     * Test attribute "meets_customer_expectation"
     */
    public function testPropertyMeetsCustomerExpectation()
    {
    }

    /**
     * Test attribute "latest_handover_date_time"
     */
    public function testPropertyLatestHandoverDateTime()
    {
    }

    /**
     * Test attribute "collection_method"
     */
    public function testPropertyCollectionMethod()
    {
    }
}
