<?php
/**
 * ReplenishmentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReplenishmentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ReplenishmentResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReplenishmentResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReplenishmentResponse"
     */
    public function testReplenishmentResponse()
    {
    }

    /**
     * Test attribute "replenishment_id"
     */
    public function testPropertyReplenishmentId()
    {
    }

    /**
     * Test attribute "creation_date_time"
     */
    public function testPropertyCreationDateTime()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "labeling_by_bol"
     */
    public function testPropertyLabelingByBol()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "delivery_information"
     */
    public function testPropertyDeliveryInformation()
    {
    }

    /**
     * Test attribute "pickup_appointment"
     */
    public function testPropertyPickupAppointment()
    {
    }

    /**
     * Test attribute "number_of_load_carriers"
     */
    public function testPropertyNumberOfLoadCarriers()
    {
    }

    /**
     * Test attribute "load_carriers"
     */
    public function testPropertyLoadCarriers()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "invalid_lines"
     */
    public function testPropertyInvalidLines()
    {
    }

    /**
     * Test attribute "state_transitions"
     */
    public function testPropertyStateTransitions()
    {
    }
}
