<?php
/**
 * OffersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OffersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OffersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteOffer
     *
     * Delete offer by id.
     *
     */
    public function testDeleteOffer()
    {
    }

    /**
     * Test case for getOffer
     *
     * Retrieve an offer by its offer id.
     *
     */
    public function testGetOffer()
    {
    }

    /**
     * Test case for getOfferExport
     *
     * Retrieve an offer export file by offer export id.
     *
     */
    public function testGetOfferExport()
    {
    }

    /**
     * Test case for postOffer
     *
     * Create a new offer.
     *
     */
    public function testPostOffer()
    {
    }

    /**
     * Test case for postOfferExport
     *
     * Request an offer export file.
     *
     */
    public function testPostOfferExport()
    {
    }

    /**
     * Test case for putOffer
     *
     * Update an offer.
     *
     */
    public function testPutOffer()
    {
    }

    /**
     * Test case for updateOfferPrice
     *
     * Update price(s) for offer by id.
     *
     */
    public function testUpdateOfferPrice()
    {
    }

    /**
     * Test case for updateOfferStock
     *
     * Update stock for offer by id.
     *
     */
    public function testUpdateOfferStock()
    {
    }
}
