<?php
/**
 * ReplenishmentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v5
 *
 * The bol.com API for Retailers.
 *
 * OpenAPI spec version: 5.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ReplenishmentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReplenishmentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getLoadCarrierLabels
     *
     * Get load carrier labels.
     *
     */
    public function testGetLoadCarrierLabels()
    {
    }

    /**
     * Test case for getPickList
     *
     * Get pick list.
     *
     */
    public function testGetPickList()
    {
    }

    /**
     * Test case for getReplenishment
     *
     * Get a replenishment by replenishment id.
     *
     */
    public function testGetReplenishment()
    {
    }

    /**
     * Test case for getReplenishments
     *
     * Get replenishments.
     *
     */
    public function testGetReplenishments()
    {
    }

    /**
     * Test case for postPickupTimeSlots
     *
     * Post pickup time slots.
     *
     */
    public function testPostPickupTimeSlots()
    {
    }

    /**
     * Test case for postProductLabels
     *
     * Post product labels.
     *
     */
    public function testPostProductLabels()
    {
    }

    /**
     * Test case for postReplenishment
     *
     * Post replenishment.
     *
     */
    public function testPostReplenishment()
    {
    }

    /**
     * Test case for putReplenishment
     *
     * Update replenishment.
     *
     */
    public function testPutReplenishment()
    {
    }
}
